// registry/react/ui/calendar.tsx
"use client"

import * as React from "react"
import {
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
} from "lucide-react"
import {
  DayPicker,
  getDefaultClassNames,
  type DayButton,
} from "react-day-picker"

import { cn } from "@/lib/utils"
import { Button, buttonVariants } from "@/registry/react/ui/button"

function Calendar({
  className,
  classNames,
  showOutsideDays = true,
  captionLayout = "label",
  buttonVariant = "ghost",
  formatters,
  components,
  ...props
}: React.ComponentProps<typeof DayPicker> & {
  buttonVariant?: React.ComponentProps<typeof Button>["variant"]
}) {
  const defaultClassNames = getDefaultClassNames()

  return (
    <DayPicker
      showOutsideDays={showOutsideDays}
      className={cn(
        "group/calendar bg-transparent p-3 [--cell-size:--spacing(8)] [[data-slot=card-content]_&]:bg-transparent [[data-slot=popover-content]_&]:bg-transparent",
        String.raw`rtl:**:[.rdp-button\_next>svg]:rotate-180`,
        String.raw`rtl:**:[.rdp-button\_previous>svg]:rotate-180`,
        className
      )}
      captionLayout={captionLayout}
      formatters={{
        formatMonthDropdown: (date) =>
          date.toLocaleString("default", { month: "short" }),
        ...formatters,
      }}
      classNames={{
        root: cn("w-fit", defaultClassNames.root),
        months: cn(
          "relative flex flex-col gap-4 md:flex-row",
          defaultClassNames.months
        ),
        month: cn("flex w-full flex-col gap-4", defaultClassNames.month),
        nav: cn(
          "absolute inset-x-0 top-0 flex w-full items-center justify-between gap-1",
          defaultClassNames.nav
        ),
        button_previous: cn(
          buttonVariants({ variant: buttonVariant }),
          "size-(--cell-size) p-0 select-none aria-disabled:opacity-50",
          defaultClassNames.button_previous
        ),
        button_next: cn(
          buttonVariants({ variant: buttonVariant }),
          "size-(--cell-size) p-0 select-none aria-disabled:opacity-50",
          defaultClassNames.button_next
        ),
        month_caption: cn(
          "flex h-(--cell-size) w-full items-center justify-center px-(--cell-size)",
          defaultClassNames.month_caption
        ),
        dropdowns: cn(
          "flex h-(--cell-size) w-full items-center justify-center gap-1.5 text-sm font-medium",
          defaultClassNames.dropdowns
        ),
        dropdown_root: cn(
          "relative rounded-md border border-border bg-card has-focus:border-ring has-focus:ring-[3px] has-focus:ring-ring/35",
          defaultClassNames.dropdown_root
        ),
        dropdown: cn(
          "absolute inset-0 bg-popover opacity-0",
          defaultClassNames.dropdown
        ),
        caption_label: cn(
          "font-medium select-none",
          captionLayout === "label"
            ? "text-sm"
            : "flex h-8 items-center gap-1 rounded-md pr-1 pl-2 text-sm [&>svg]:size-3.5 [&>svg]:text-muted-foreground",
          defaultClassNames.caption_label
        ),
        table: "w-full border-collapse",
        weekdays: cn("flex", defaultClassNames.weekdays),
        weekday: cn(
          "flex-1 rounded-md text-[0.8rem] font-normal text-muted-foreground select-none",
          defaultClassNames.weekday
        ),
        week: cn("mt-2 flex w-full", defaultClassNames.week),
        week_number_header: cn(
          "w-(--cell-size) select-none",
          defaultClassNames.week_number_header
        ),
        week_number: cn(
          "text-[0.8rem] text-muted-foreground select-none",
          defaultClassNames.week_number
        ),
        day: cn(
          "group/day relative aspect-square h-full w-full p-0 text-center select-none [&:last-child[data-selected=true]_button]:rounded-r-md",
          props.showWeekNumber
            ? "[&:nth-child(2)[data-selected=true]_button]:rounded-l-md"
            : "[&:first-child[data-selected=true]_button]:rounded-l-md",
          defaultClassNames.day
        ),
        range_start: cn(
          "rounded-l-md bg-accent",
          defaultClassNames.range_start
        ),
        range_middle: cn("rounded-none", defaultClassNames.range_middle),
        range_end: cn("rounded-r-md bg-accent", defaultClassNames.range_end),
        today: cn(
          "rounded-md bg-accent text-accent-foreground data-[selected=true]:rounded-none",
          defaultClassNames.today
        ),
        outside: cn(
          "text-muted-foreground aria-selected:text-muted-foreground",
          defaultClassNames.outside
        ),
        disabled: cn(
          "text-muted-foreground opacity-50",
          defaultClassNames.disabled
        ),
        hidden: cn("invisible", defaultClassNames.hidden),
        ...classNames,
      }}
      components={{
        Root: ({ className, rootRef, ...props }) => {
          return (
            <div
              data-slot="calendar"
              ref={rootRef}
              className={cn(className)}
              {...props}
            />
          )
        },
        Chevron: ({ className, orientation, ...props }) => {
          if (orientation === "left") {
            return (
              <ChevronLeftIcon className={cn("size-4", className)} {...props} />
            )
          }

          if (orientation === "right") {
            return (
              <ChevronRightIcon
                className={cn("size-4", className)}
                {...props}
              />
            )
          }

          return (
            <ChevronDownIcon className={cn("size-4", className)} {...props} />
          )
        },
        DayButton: CalendarDayButton,
        WeekNumber: ({ children, ...props }) => {
          return (
            <td {...props}>
              <div className="flex size-(--cell-size) items-center justify-center text-center">
                {children}
              </div>
            </td>
          )
        },
        ...components,
      }}
      {...props}
    />
  )
}

function CalendarDayButton({
  className,
  day,
  modifiers,
  ...props
}: React.ComponentProps<typeof DayButton>) {
  const defaultClassNames = getDefaultClassNames()

  const ref = React.useRef<HTMLButtonElement>(null)
  React.useEffect(() => {
    if (modifiers.focused) ref.current?.focus()
  }, [modifiers.focused])

  return (
    <Button
      ref={ref}
      variant="ghost"
      size="icon"
      data-day={day.date.toLocaleDateString()}
      data-selected-single={
        modifiers.selected &&
        !modifiers.range_start &&
        !modifiers.range_end &&
        !modifiers.range_middle
      }
      data-range-start={modifiers.range_start}
      data-range-end={modifiers.range_end}
      data-range-middle={modifiers.range_middle}
      className={cn(
        "flex aspect-square size-auto w-full min-w-(--cell-size) flex-col gap-1 leading-none font-normal group-data-[focused=true]/day:relative group-data-[focused=true]/day:z-10 group-data-[focused=true]/day:border-ring group-data-[focused=true]/day:ring-[3px] group-data-[focused=true]/day:ring-ring/35 data-[range-end=true]:rounded-md data-[range-end=true]:rounded-r-md data-[range-end=true]:bg-primary data-[range-end=true]:text-primary-foreground data-[range-middle=true]:rounded-none data-[range-middle=true]:bg-accent data-[range-middle=true]:text-accent-foreground data-[range-start=true]:rounded-md data-[range-start=true]:rounded-l-md data-[range-start=true]:bg-primary data-[range-start=true]:text-primary-foreground data-[selected-single=true]:bg-primary data-[selected-single=true]:text-primary-foreground dark:hover:text-accent-foreground [&>span]:text-xs [&>span]:opacity-70",
        defaultClassNames.day,
        className
      )}
      {...props}
    />
  )
}

export { Calendar, CalendarDayButton }

// registry/solid/ui/calendar.tsx
import type { ComponentProps, ValidComponent } from "solid-js"
import { For, Match, Show, Switch, splitProps } from "solid-js"
import CalendarPrimitive from "@corvu/calendar"
import ChevronLeftIcon from "lucide-solid/icons/chevron-left"
import ChevronRightIcon from "lucide-solid/icons/chevron-right"

import { cx } from "@/registry/solid/lib/cva"

import { buttonVariants } from "./button"

export type CalendarProps = ComponentProps<typeof CalendarPrimitive> & {
  class?: string
  defaultMonth?: Date
  selected?: Date
  today?: Date
  showOutsideDays?: boolean
  locale?: Intl.LocalesArgument
}

export const Calendar = (props: CalendarProps) => {
  const [local, rest] = splitProps(props, [
    "class",
    "children",
    "defaultMonth",
    "selected",
    "today",
    "showOutsideDays",
    "locale",
  ])

  if (local.children) {
    return <CalendarPrimitive data-slot="calendar" {...props} />
  }

  const month = () => local.defaultMonth ?? local.selected ?? new Date()
  const today = () => local.today ?? new Date()
  const showOutsideDays = () => local.showOutsideDays ?? true
  const monthStart = () => new Date(month().getFullYear(), month().getMonth(), 1)
  const label = () =>
    monthStart().toLocaleString(local.locale, {
      month: "long",
      year: "numeric",
    })
  const weekdays = () =>
    Array.from({ length: 7 }, (_, index) =>
      new Date(2021, 7, index + 1).toLocaleDateString(local.locale, {
        weekday: "short",
      }),
    )
  const sameDay = (a?: Date, b?: Date) =>
    !!a &&
    !!b &&
    a.getFullYear() === b.getFullYear() &&
    a.getMonth() === b.getMonth() &&
    a.getDate() === b.getDate()
  const days = () => {
    const start = monthStart()
    const first = new Date(start)
    first.setDate(1 - start.getDay())
    const daysInMonth = new Date(
      start.getFullYear(),
      start.getMonth() + 1,
      0,
    ).getDate()
    const weekCount = Math.ceil((start.getDay() + daysInMonth) / 7)

    return Array.from({ length: weekCount * 7 }, (_, index) => {
      const date = new Date(first)
      date.setDate(first.getDate() + index)
      return {
        date,
        outside: date.getMonth() !== start.getMonth(),
        selected: sameDay(date, local.selected),
        today: sameDay(date, today()),
      }
    })
  }

  return (
    <div
      data-slot="calendar"
      class={cx(
        "group/calendar w-fit bg-transparent p-3 [--cell-size:--spacing(8)]",
        local.class,
      )}
      {...rest}
    >
      <div class="relative flex flex-col gap-4">
        <div class="absolute inset-x-0 top-0 flex w-full items-center justify-between gap-1">
          <button
            type="button"
            aria-label="Previous month"
            class={buttonVariants({
              variant: "ghost",
              size: "icon",
              class: "size-(--cell-size) p-0 select-none",
            })}
          >
            <ChevronLeftIcon class="size-4" />
          </button>
          <button
            type="button"
            aria-label="Next month"
            class={buttonVariants({
              variant: "ghost",
              size: "icon",
              class: "size-(--cell-size) p-0 select-none",
            })}
          >
            <ChevronRightIcon class="size-4" />
          </button>
        </div>
        <div class="flex h-(--cell-size) w-full items-center justify-center px-(--cell-size)">
          <span class="text-sm font-medium select-none">{label()}</span>
        </div>
        <table class="w-full border-collapse">
          <thead>
            <tr class="flex">
              <For each={weekdays()}>
                {(day) => (
                  <th class="flex-1 rounded-md text-[0.8rem] font-normal text-muted-foreground select-none">
                    {day}
                  </th>
                )}
              </For>
            </tr>
          </thead>
          <tbody>
            <For
              each={Array.from(
                { length: days().length / 7 },
                (_, index) => index,
              )}
            >
              {(week) => (
                <tr class="mt-2 flex w-full">
                  <For each={days().slice(week * 7, week * 7 + 7)}>
                    {(day) => (
                      <td class="group/day relative aspect-square h-full w-full p-0 text-center select-none">
                        <Show when={showOutsideDays() || !day.outside}>
                          <button
                            type="button"
                            data-day={day.date.toLocaleDateString(
                              local.locale,
                            )}
                            data-selected-single={day.selected}
                            data-today={day.today}
                            class={buttonVariants({
                              variant: "ghost",
                              size: "icon",
                              class:
                                "flex aspect-square size-auto w-full min-w-(--cell-size) flex-col gap-1 leading-none font-normal data-[today=true]:bg-accent data-[today=true]:text-accent-foreground data-[selected-single=true]:bg-primary! data-[selected-single=true]:text-primary-foreground! dark:hover:text-accent-foreground",
                            })}
                          >
                            {day.date.getDate()}
                          </button>
                        </Show>
                      </td>
                    )}
                  </For>
                </tr>
              )}
            </For>
          </tbody>
        </table>
      </div>
    </div>
  )
}

export type CalendarNavProps<T extends ValidComponent = "button"> =
  ComponentProps<typeof CalendarPrimitive.Nav<T>>

export const CalendarNav = <T extends ValidComponent = "button">(
  props: CalendarNavProps<T>,
) => {
  const [, rest] = splitProps(props as CalendarNavProps, ["action", "class"])

  return (
    <CalendarPrimitive.Nav
      data-slot="calendar-nav"
      action={props.action}
      class={buttonVariants({
        variant: "outline",
        class: [
          "size-7 bg-transparent p-0 opacity-50 hover:opacity-100",
          props.class,
        ],
      })}
      {...rest}
    >
      <Switch>
        <Match
          when={props.action === "prev-year" || props.action === "prev-month"}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="size-4"
            viewBox="0 0 24 24"
          >
            <path
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="m15 18l-6-6l6-6"
            />
          </svg>
        </Match>
        <Match
          when={props.action === "next-year" || props.action === "next-month"}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="size-4"
            viewBox="0 0 24 24"
          >
            <path
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="m9 18l6-6l-6-6"
            />
          </svg>
        </Match>
      </Switch>
    </CalendarPrimitive.Nav>
  )
}

export type CalendarLabelProps<T extends ValidComponent = "h2"> =
  ComponentProps<typeof CalendarPrimitive.Label<T>>

export const CalendarLabel = <T extends ValidComponent = "h2">(
  props: CalendarLabelProps<T>,
) => {
  const [, rest] = splitProps(props as CalendarLabelProps, ["class"])

  return (
    <CalendarPrimitive.Label
      data-slot="calendar-label"
      class={cx("text-sm font-medium", props.class)}
      {...rest}
    />
  )
}

export type CalendarTableProps<T extends ValidComponent = "table"> =
  ComponentProps<typeof CalendarPrimitive.Table<T>>

export const CalendarTable = <T extends ValidComponent = "table">(
  props: CalendarTableProps<T>,
) => {
  return <CalendarPrimitive.Table data-slot="calendar-table" {...props} />
}

export type CalendarHeadCellProps<T extends ValidComponent = "th"> =
  ComponentProps<typeof CalendarPrimitive.HeadCell<T>>

export const CalendarHeadCell = <T extends ValidComponent = "th">(
  props: CalendarHeadCellProps<T>,
) => {
  const [, rest] = splitProps(props as CalendarHeadCellProps, ["class"])

  return (
    <CalendarPrimitive.HeadCell
      data-slot="calendar-head-cell"
      class={cx(
        "text-muted-foreground w-8 rounded-md text-[0.8rem] font-normal",
        props.class,
      )}
      {...rest}
    />
  )
}

export type CalendarCellProps<T extends ValidComponent = "td"> = ComponentProps<
  typeof CalendarPrimitive.Cell<T>
>

export const CalendarCell = <T extends ValidComponent = "td">(
  props: CalendarCellProps<T>,
) => {
  const [, rest] = splitProps(props as CalendarCellProps, ["class"])

  return (
    <CalendarPrimitive.Cell
      data-slot="calendar-cell"
      class={cx(
        "has-[[data-in-range]]:bg-accent relative p-0 text-center text-sm focus-within:relative focus-within:z-20 has-[[data-disabled][data-selected]]:opacity-50 has-[[data-in-range]]:first:rounded-l-md has-[[data-in-range]]:last:rounded-r-md has-[[data-range-end]]:rounded-r-md has-[[data-range-start]]:rounded-l-md",
        props.class,
      )}
      {...rest}
    />
  )
}

export type CalendarCellTriggerProps<T extends ValidComponent = "button"> =
  ComponentProps<typeof CalendarPrimitive.CellTrigger<T>>

export const CalendarCellTrigger = <T extends ValidComponent = "button">(
  props: CalendarCellTriggerProps<T>,
) => {
  const [, rest] = splitProps(props as CalendarCellTriggerProps, ["class"])

  return (
    <CalendarPrimitive.CellTrigger
      data-slot="calendar-cell-trigger"
      class={buttonVariants({
        variant: "ghost",
        class: [
          "size-8 p-0 font-normal aria-selected:opacity-100",
          "data-[today]:bg-accent data-[today]:text-accent-foreground dark:data-[today]:focus-visible:ring-secondary",
          "aria-selected:not-[[data-in-range]]:bg-primary! aria-selected:not-[[data-in-range]]:text-primary-foreground! aria-selected:not-[[data-in-range]]:hover:bg-primary aria-selected:not-[[data-in-range]]:hover:text-primary-foreground",
          "data-[range-start]:aria-selected:bg-primary data-[range-start]:aria-selected:text-primary-foreground data-[range-start]:aria-selected:hover:bg-primary! data-[range-start]:aria-selected:hover:text-primary-foreground!",
          "data-[range-end]:aria-selected:bg-primary data-[range-end]:aria-selected:text-primary-foreground data-[range-end]:aria-selected:hover:bg-primary! data-[range-end]:aria-selected:hover:text-primary-foreground!",
          props.class,
        ],
      })}
      {...rest}
    />
  )
}
