// registry/react/ui/drawer.tsx
"use client"

import * as React from "react"
import { Drawer as DrawerPrimitive } from "vaul"

import { cn } from "@/lib/utils"

function Drawer({
  ...props
}: React.ComponentProps<typeof DrawerPrimitive.Root>) {
  return <DrawerPrimitive.Root data-slot="drawer" {...props} />
}

function DrawerTrigger({
  ...props
}: React.ComponentProps<typeof DrawerPrimitive.Trigger>) {
  return <DrawerPrimitive.Trigger data-slot="drawer-trigger" {...props} />
}

function DrawerPortal({
  ...props
}: React.ComponentProps<typeof DrawerPrimitive.Portal>) {
  return <DrawerPrimitive.Portal data-slot="drawer-portal" {...props} />
}

function DrawerClose({
  ...props
}: React.ComponentProps<typeof DrawerPrimitive.Close>) {
  return <DrawerPrimitive.Close data-slot="drawer-close" {...props} />
}

function DrawerOverlay({
  className,
  ...props
}: React.ComponentProps<typeof DrawerPrimitive.Overlay>) {
  return (
    <DrawerPrimitive.Overlay
      data-slot="drawer-overlay"
      className={cn(
        "fixed inset-0 z-50 bg-black/35 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:animate-in data-[state=open]:fade-in-0",
        className
      )}
      {...props}
    />
  )
}

function DrawerContent({
  className,
  children,
  ...props
}: React.ComponentProps<typeof DrawerPrimitive.Content>) {
  return (
    <DrawerPortal data-slot="drawer-portal">
      <DrawerOverlay />
      <DrawerPrimitive.Content
        data-slot="drawer-content"
        className={cn(
          "group/drawer-content fixed z-50 flex h-auto flex-col bg-card text-card-foreground shadow-xl outline-none",
          "data-[vaul-drawer-direction=top]:inset-x-0 data-[vaul-drawer-direction=top]:top-0 data-[vaul-drawer-direction=top]:mb-24 data-[vaul-drawer-direction=top]:max-h-[80vh] data-[vaul-drawer-direction=top]:rounded-b-lg data-[vaul-drawer-direction=top]:border-b",
          "data-[vaul-drawer-direction=bottom]:inset-x-0 data-[vaul-drawer-direction=bottom]:bottom-0 data-[vaul-drawer-direction=bottom]:mt-24 data-[vaul-drawer-direction=bottom]:max-h-[80vh] data-[vaul-drawer-direction=bottom]:rounded-t-lg data-[vaul-drawer-direction=bottom]:border-t",
          "data-[vaul-drawer-direction=right]:inset-y-0 data-[vaul-drawer-direction=right]:right-0 data-[vaul-drawer-direction=right]:w-3/4 data-[vaul-drawer-direction=right]:border-l data-[vaul-drawer-direction=right]:sm:max-w-sm",
          "data-[vaul-drawer-direction=left]:inset-y-0 data-[vaul-drawer-direction=left]:left-0 data-[vaul-drawer-direction=left]:w-3/4 data-[vaul-drawer-direction=left]:border-r data-[vaul-drawer-direction=left]:sm:max-w-sm",
          className
        )}
        {...props}
      >
        <div className="mx-auto mt-4 hidden h-1.5 w-[88px] shrink-0 rounded-full bg-border group-data-[vaul-drawer-direction=bottom]/drawer-content:block" />
        {children}
      </DrawerPrimitive.Content>
    </DrawerPortal>
  )
}

function DrawerHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="drawer-header"
      className={cn(
        "flex flex-col gap-1.5 p-6 group-data-[vaul-drawer-direction=bottom]/drawer-content:text-center group-data-[vaul-drawer-direction=top]/drawer-content:text-center md:text-left",
        className
      )}
      {...props}
    />
  )
}

function DrawerFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="drawer-footer"
      className={cn("mt-auto flex flex-col gap-2 p-6", className)}
      {...props}
    />
  )
}

function DrawerTitle({
  className,
  ...props
}: React.ComponentProps<typeof DrawerPrimitive.Title>) {
  return (
    <DrawerPrimitive.Title
      data-slot="drawer-title"
      className={cn("font-semibold text-foreground", className)}
      {...props}
    />
  )
}

function DrawerDescription({
  className,
  ...props
}: React.ComponentProps<typeof DrawerPrimitive.Description>) {
  return (
    <DrawerPrimitive.Description
      data-slot="drawer-description"
      className={cn("text-sm text-muted-foreground", className)}
      {...props}
    />
  )
}

export {
  Drawer,
  DrawerPortal,
  DrawerOverlay,
  DrawerTrigger,
  DrawerClose,
  DrawerContent,
  DrawerHeader,
  DrawerFooter,
  DrawerTitle,
  DrawerDescription,
}

// registry/solid/ui/drawer.tsx
import type { ComponentProps, ValidComponent } from "solid-js"
import { Show, mergeProps, splitProps } from "solid-js"
import type { DynamicProps } from "@corvu/drawer"
import DrawerPrimitive from "@corvu/drawer"

import { cx } from "@/registry/solid/lib/cva"

export const DrawerPortal = DrawerPrimitive.Portal

export type DrawerProps = ComponentProps<typeof DrawerPrimitive>

export const Drawer = (props: DrawerProps) => {
  return <DrawerPrimitive data-slot="drawer" {...props} />
}

export type DrawerTriggerProps<T extends ValidComponent = "button"> =
  ComponentProps<typeof DrawerPrimitive.Trigger<T>>

export const DrawerTrigger = <T extends ValidComponent = "button">(
  props: DrawerTriggerProps<T>,
) => {
  return <DrawerPrimitive.Trigger data-slot="drawer-trigger" {...props} />
}

export type DrawerCloseProps<T extends ValidComponent = "button"> =
  ComponentProps<typeof DrawerPrimitive.Close<T>>

export const DrawerClose = <T extends ValidComponent = "button">(
  props: DrawerCloseProps<T>,
) => {
  return <DrawerPrimitive.Close data-slot="drawer-close" {...props} />
}

export type DrawerContentProps<T extends ValidComponent = "div"> =
  ComponentProps<typeof DrawerPrimitive.Content<T>> & {
    withHandle?: boolean
  }

export const DrawerContent = <T extends ValidComponent = "div">(
  props: DrawerContentProps<T>,
) => {
  const context = DrawerPrimitive.useContext()

  const merge = mergeProps<DrawerContentProps[]>(
    {
      withHandle: context.side() === "bottom",
    },
    props as DrawerContentProps,
  )
  const [, rest] = splitProps(merge, ["class", "children", "withHandle"])

  return (
    <>
      <DrawerPrimitive.Overlay
        data-slot="drawer-overlay"
        class="fixed inset-0 z-50 bg-black/35 data-[transitioning]:transition-colors data-[transitioning]:duration-500 data-[transitioning]:ease-[cubic-bezier(0.32,0.72,0,1)]"
        style={{
          "background-color": `rgb(0 0 0 / ${0.35 * context.openPercentage()}`,
        }}
      />
      <DrawerPrimitive.Content
        data-slot="drawer-content"
        data-side={context.side()}
        class={cx(
          "group/drawer-content fixed z-50 flex h-auto flex-col bg-card text-card-foreground shadow-md outline-none after:absolute after:bg-inherit data-[transitioning]:transition-transform data-[transitioning]:duration-500 data-[transitioning]:ease-[cubic-bezier(0.32,0.72,0,1)]",
          context.side() === "bottom" && [
            "inset-x-0 bottom-0 mt-24 max-h-[80vh] rounded-t-lg border-t",
            "after:inset-x-0 after:top-[calc(100%-1px)] after:h-1/2",
          ],
          context.side() === "top" && [
            "inset-x-0 top-0 mb-24 max-h-[80vh] rounded-b-lg border-b",
            "after:inset-x-0 after:bottom-[calc(100%-1px)] after:h-1/2",
          ],
          context.side() === "left" && [
            "inset-y-0 left-0 w-3/4 border-r sm:max-w-sm",
            "after:inset-y-0 after:right-[calc(100%-1px)] after:w-1/2",
          ],
          context.side() === "right" && [
            "inset-y-0 right-0 w-3/4 border-l sm:max-w-sm",
            "after:inset-y-0 after:left-[calc(100%-1px)] after:w-1/2",
          ],
          props.class,
        )}
        {...rest}
      >
        <Show when={props.withHandle}>
          <div
            class={cx(
              "shrink-0 self-center rounded-full bg-border",
              context.side() === "bottom" && "mt-4 h-1.5 w-[88px]",
            )}
          />
        </Show>
        {props.children}
      </DrawerPrimitive.Content>
    </>
  )
}

export type DrawerLabelProps<T extends ValidComponent = "h2"> = ComponentProps<
  typeof DrawerPrimitive.Label<T>
>

export const DrawerLabel = <T extends ValidComponent = "h2">(
  props: DynamicProps<T, DrawerLabelProps<T>>,
) => {
  const [, rest] = splitProps(props as DrawerLabelProps, ["class"])

  return (
    <DrawerPrimitive.Label
      data-slot="drawer-label"
      class={cx("font-semibold text-foreground", props.class)}
      {...rest}
    />
  )
}

export type DrawerTitleProps<T extends ValidComponent = "h2"> = ComponentProps<
  typeof DrawerPrimitive.Label<T>
>

export const DrawerTitle = <T extends ValidComponent = "h2">(
  props: DynamicProps<T, DrawerTitleProps<T>>,
) => {
  const [, rest] = splitProps(props as DrawerTitleProps, ["class"])

  return (
    <DrawerPrimitive.Label
      data-slot="drawer-title"
      class={cx("font-semibold text-foreground", props.class)}
      {...rest}
    />
  )
}

export type DrawerDescriptionProps<T extends ValidComponent = "p"> =
  ComponentProps<typeof DrawerPrimitive.Description<T>>

export const DrawerDescription = <T extends ValidComponent = "p">(
  props: DynamicProps<T, DrawerDescriptionProps<T>>,
) => {
  const [, rest] = splitProps(props as DrawerDescriptionProps, ["class"])

  return (
    <DrawerPrimitive.Description
      data-slot="drawer-description"
      class={cx("text-muted-foreground text-sm", props.class)}
      {...rest}
    />
  )
}

export type DrawerHeaderProps = ComponentProps<"div">

export const DrawerHeader = (props: DrawerHeaderProps) => {
  const [, rest] = splitProps(props, ["class"])

  return (
    <div
      data-slot="drawer-header"
      class={cx(
        "flex flex-col gap-1.5 p-6 group-data-[side=bottom]/drawer-content:text-center group-data-[side=top]/drawer-content:text-center md:text-left",
        props.class,
      )}
      {...rest}
    />
  )
}

export type DrawerFooterProps = ComponentProps<"div">

export const DrawerFooter = (props: DrawerFooterProps) => {
  const [, rest] = splitProps(props, ["class"])

  return (
    <div
      data-slot="drawer-footer"
      class={cx("mt-auto flex flex-col gap-2 p-6", props.class)}
      {...rest}
    />
  )
}
