// registry/react/ui/hover-card.tsx
"use client"

import * as React from "react"
import { HoverCard as HoverCardPrimitive } from "radix-ui"

import { cn } from "@/lib/utils"

function HoverCard({
  ...props
}: React.ComponentProps<typeof HoverCardPrimitive.Root>) {
  return <HoverCardPrimitive.Root data-slot="hover-card" {...props} />
}

function HoverCardTrigger({
  ...props
}: React.ComponentProps<typeof HoverCardPrimitive.Trigger>) {
  return (
    <HoverCardPrimitive.Trigger data-slot="hover-card-trigger" {...props} />
  )
}

function HoverCardContent({
  className,
  align = "center",
  sideOffset = 4,
  ...props
}: React.ComponentProps<typeof HoverCardPrimitive.Content>) {
  return (
    <HoverCardPrimitive.Portal data-slot="hover-card-portal">
      <HoverCardPrimitive.Content
        data-slot="hover-card-content"
        align={align}
        sideOffset={sideOffset}
        className={cn(
          "z-50 w-64 origin-(--radix-hover-card-content-transform-origin) rounded-lg border bg-popover p-4 text-popover-foreground shadow-md outline-hidden data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95",
          className
        )}
        {...props}
      />
    </HoverCardPrimitive.Portal>
  )
}

export { HoverCard, HoverCardTrigger, HoverCardContent }

// registry/solid/ui/hover-card.tsx
import type { ComponentProps, ValidComponent } from "solid-js"
import { splitProps } from "solid-js"
import { HoverCard as HoverCardPrimitive } from "@kobalte/core/hover-card"

import { cx } from "@/registry/solid/lib/cva"

export const HoverCardPortal = HoverCardPrimitive.Portal

export type HoverCardProps = ComponentProps<typeof HoverCardPrimitive>

export const HoverCard = (props: HoverCardProps) => {
  return <HoverCardPrimitive data-slot="hover-card" {...props} />
}

export type HoverCardTriggerProps<T extends ValidComponent = "button"> =
  ComponentProps<typeof HoverCardPrimitive.Trigger<T>>

export const HoverCardTrigger = <T extends ValidComponent = "button">(
  props: HoverCardTriggerProps<T>,
) => {
  return (
    <HoverCardPrimitive.Trigger data-slot="hover-card-trigger" {...props} />
  )
}

export type HoverCardContentProps<T extends ValidComponent = "div"> =
  ComponentProps<typeof HoverCardPrimitive.Content<T>>

export const HoverCardContent = <T extends ValidComponent = "div">(
  props: HoverCardContentProps<T>,
) => {
  const [, rest] = splitProps(props as HoverCardContentProps, ["class"])

  return (
    <HoverCardPrimitive.Content
      data-slot="hover-card-content"
      class={cx(
        "bg-popover text-popover-foreground data-[expanded]:animate-in data-[closed]:animate-out data-[closed]:fade-out-0 data-[expanded]:fade-in-0 data-[closed]:zoom-out-95 data-[expanded]:zoom-in-95 z-50 w-64 origin-(--kb-hovercard-content-transform-origin) rounded-md border p-4 shadow-md outline-hidden",
        "[[data-popper-positioner][style*='--kb-popper-content-transform-origin:_top']>[data-slot=hover-card-content]]:slide-in-from-top-2 [[data-popper-positioner][style*='--kb-popper-content-transform-origin:_bottom']>[data-slot=hover-card-content]]:slide-in-from-bottom-2 [[data-popper-positioner][style*='--kb-popper-content-transform-origin:_left']>[data-slot=hover-card-content]]:slide-in-from-left-2 [[data-popper-positioner][style*='--kb-popper-content-transform-origin:_right']>[data-slot=hover-card-content]]:slide-in-from-right-2",
        props.class,
      )}
      {...rest}
    />
  )
}
