// registry/react/ui/resizable.tsx
"use client"

import { GripVerticalIcon } from "lucide-react"
import * as ResizablePrimitive from "react-resizable-panels"

import { cn } from "@/lib/utils"

function ResizablePanelGroup({
  className,
  ...props
}: ResizablePrimitive.GroupProps) {
  return (
    <ResizablePrimitive.Group
      data-slot="resizable-panel-group"
      className={cn(
        "flex h-full w-full aria-[orientation=vertical]:flex-col",
        className
      )}
      {...props}
    />
  )
}

function ResizablePanel({ ...props }: ResizablePrimitive.PanelProps) {
  return <ResizablePrimitive.Panel data-slot="resizable-panel" {...props} />
}

function ResizableHandle({
  withHandle,
  className,
  ...props
}: ResizablePrimitive.SeparatorProps & {
  withHandle?: boolean
}) {
  return (
    <ResizablePrimitive.Separator
      data-slot="resizable-handle"
      className={cn(
        "relative flex w-px items-center justify-center bg-border after:absolute after:inset-y-0 after:left-1/2 after:w-1 after:-translate-x-1/2 focus-visible:ring-[3px] focus-visible:ring-ring/35 focus-visible:outline-hidden aria-[orientation=horizontal]:h-px aria-[orientation=horizontal]:w-full aria-[orientation=horizontal]:after:left-0 aria-[orientation=horizontal]:after:h-1 aria-[orientation=horizontal]:after:w-full aria-[orientation=horizontal]:after:translate-x-0 aria-[orientation=horizontal]:after:-translate-y-1/2 [&[aria-orientation=horizontal]>div]:rotate-90",
        className
      )}
      {...props}
    >
      {withHandle && (
        <div className="z-10 flex h-4 w-3 items-center justify-center rounded-md border bg-card text-muted-foreground">
          <GripVerticalIcon className="size-2.5" />
        </div>
      )}
    </ResizablePrimitive.Separator>
  )
}

export { ResizableHandle, ResizablePanel, ResizablePanelGroup }

// registry/solid/ui/resizable.tsx
import { splitProps, type JSX } from "solid-js"
import { GripVerticalIcon } from "lucide-solid"
import { cn } from "@/registry/solid/lib/utils"
function ResizablePanelGroup(props: JSX.HTMLAttributes<HTMLDivElement> & { direction?: "horizontal" | "vertical" }) { const [l,r]=splitProps(props,["class","direction"]); return <div data-slot="resizable-panel-group" data-direction={l.direction||"horizontal"} class={cn("flex h-full w-full data-[direction=vertical]:flex-col",l.class)} {...r}/> }
function ResizablePanel(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="resizable-panel" class={cn("min-w-0 flex-1",l.class)} {...r}/> }
function ResizableHandle(props: JSX.HTMLAttributes<HTMLDivElement> & { withHandle?: boolean }) { const [l,r]=splitProps(props,["class","withHandle"]); return <div data-slot="resizable-handle" class={cn("relative flex w-px items-center justify-center bg-border after:absolute after:inset-y-0 after:left-1/2 after:w-1 after:-translate-x-1/2 focus-visible:ring-[3px] focus-visible:ring-ring/35 focus-visible:outline-hidden",l.class)} {...r}>{l.withHandle && <div class="z-10 flex h-4 w-3 items-center justify-center rounded-md border bg-card text-muted-foreground"><GripVerticalIcon class="size-2.5" /></div>}</div> }
export { ResizablePanelGroup, ResizablePanel, ResizableHandle }
