// registry/react/ui/switch.tsx
"use client"

import * as React from "react"
import { Switch as SwitchPrimitive } from "radix-ui"

import { cn } from "@/lib/utils"

function Switch({
  className,
  size = "default",
  ...props
}: React.ComponentProps<typeof SwitchPrimitive.Root> & {
  size?: "sm" | "default"
}) {
  return (
    <SwitchPrimitive.Root
      data-slot="switch"
      data-size={size}
      className={cn(
        "peer group/switch inline-flex shrink-0 items-center rounded-full border border-border bg-border/70 transition-[background-color,border-color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/35 disabled:cursor-not-allowed disabled:opacity-50 data-[size=default]:h-5 data-[size=default]:w-9 data-[size=sm]:h-4 data-[size=sm]:w-7 data-[state=checked]:border-primary data-[state=checked]:bg-primary data-[state=unchecked]:hover:border-input dark:data-[state=unchecked]:bg-input/80",
        className
      )}
      {...props}
    >
      <SwitchPrimitive.Thumb
        data-slot="switch-thumb"
        className={cn(
          "pointer-events-none block rounded-full bg-card ring-0 shadow-[0_1px_2px_rgb(0_0_0/0.18)] transition-transform group-data-[size=default]/switch:size-4 group-data-[size=sm]/switch:size-3 data-[state=checked]:translate-x-[calc(100%-1px)] data-[state=unchecked]:translate-x-0 dark:data-[state=checked]:bg-primary-foreground dark:data-[state=unchecked]:bg-foreground"
        )}
      />
    </SwitchPrimitive.Root>
  )
}

export { Switch }

// registry/solid/ui/switch.tsx
import { splitProps, type ComponentProps, type ValidComponent } from "solid-js"
import { Switch as SwitchPrimitive } from "@kobalte/core/switch"

import { cx } from "@/registry/solid/lib/cva"

export type SwitchProps<T extends ValidComponent = "div"> = ComponentProps<
  typeof SwitchPrimitive<T>
> & {
  size?: "sm" | "default"
}

export const Switch = <T extends ValidComponent = "div">(
  props: SwitchProps<T>,
) => {
  const [, rest] = splitProps(props as SwitchProps, [
    "class",
    "children",
    "size",
  ])

  return (
    <SwitchPrimitive
      data-slot="switch"
      data-size={props.size ?? "default"}
      class={cx(
        "inline-flex shrink-0 items-center leading-none data-[size=default]:h-5 data-[size=sm]:h-4",
      )}
      {...rest}
    >
      {(state) => (
        <>
          <SwitchPrimitive.Input />
          <SwitchPrimitive.Control
            data-slot="switch-control"
            data-size={props.size ?? "default"}
            class={cx(
              "peer group/switch inline-flex shrink-0 items-center rounded-full border border-border bg-border/70 transition-[background-color,border-color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/35 disabled:cursor-not-allowed disabled:opacity-50 data-[size=default]:h-5 data-[size=default]:w-9 data-[size=sm]:h-4 data-[size=sm]:w-7 data-[checked]:border-primary data-[checked]:bg-primary data-[unchecked]:hover:border-input dark:data-[unchecked]:bg-input/80",
              props.class,
            )}
          >
            <SwitchPrimitive.Thumb
              data-slot="switch-thumb"
              class="pointer-events-none block rounded-full bg-card ring-0 shadow-[0_1px_2px_rgb(0_0_0/0.18)] transition-transform group-data-[size=default]/switch:size-4 group-data-[size=sm]/switch:size-3 data-[checked]:translate-x-[calc(100%-1px)] data-[unchecked]:translate-x-0 dark:data-[checked]:bg-primary-foreground dark:data-[unchecked]:bg-foreground"
            />
          </SwitchPrimitive.Control>
          {typeof props.children === "function"
            ? props.children(state)
            : props.children}
        </>
      )}
    </SwitchPrimitive>
  )
}

export type SwitchControlProps<T extends ValidComponent = "div"> =
  ComponentProps<typeof SwitchPrimitive.Control<T>>

export const SwitchControl = <T extends ValidComponent = "div">(
  props: SwitchControlProps<T>,
) => {
  const [, rest] = splitProps(props as SwitchControlProps, ["class"])

  return (
    <SwitchPrimitive.Control
      data-slot="switch-control"
      class={cx(
        "peer group/switch inline-flex h-5 w-9 shrink-0 items-center rounded-full border border-border bg-border/70 transition-[background-color,border-color,box-shadow] outline-none data-[checked]:border-primary data-[checked]:bg-primary data-[unchecked]:hover:border-input dark:data-[unchecked]:bg-input/80",
        "peer-focus-visible/switch-input:border-ring peer-focus-visible/switch-input:ring-ring/35 peer-focus-visible/switch-input:ring-[3px]",
        "data-[disabled]:cursor-not-allowed data-[disabled]:opacity-50",
        props.class,
      )}
      {...rest}
    />
  )
}

export type SwitchThumbProps<T extends ValidComponent = "div"> = ComponentProps<
  typeof SwitchPrimitive.Thumb<T>
>

export const SwitchThumb = <T extends ValidComponent = "div">(
  props: SwitchThumbProps<T>,
) => {
  const [, rest] = splitProps(props as SwitchThumbProps, ["class"])

  return (
    <SwitchPrimitive.Thumb
      data-slot="switch-thumb"
      class={cx(
        "pointer-events-none block size-4 rounded-full bg-card ring-0 shadow-[0_1px_2px_rgb(0_0_0/0.18)] transition-transform data-[checked]:translate-x-[calc(100%-1px)] data-[unchecked]:translate-x-0 dark:data-[checked]:bg-primary-foreground dark:data-[unchecked]:bg-foreground",
        props.class,
      )}
      {...rest}
    />
  )
}

export type SwitchInputProps<T extends ValidComponent = "input"> =
  ComponentProps<typeof SwitchPrimitive.Input<T>>

export const SwitchInput = <T extends ValidComponent = "input">(
  props: SwitchInputProps<T>,
) => {
  const [, rest] = splitProps(props as SwitchInputProps, ["class"])

  return (
    <SwitchPrimitive.Input
      data-slot="switch-input"
      class={cx("peer/switch-input", props.class)}
      {...rest}
    />
  )
}

export type SwitchLabelProps<T extends ValidComponent = "label"> =
  ComponentProps<typeof SwitchPrimitive.Label<T>>

export const SwitchLabel = <T extends ValidComponent = "label">(
  props: SwitchLabelProps<T>,
) => {
  const [, rest] = splitProps(props as SwitchLabelProps, ["class"])

  return (
    <SwitchPrimitive.Label
      data-slot="switch-label"
      class={cx(
        "text-sm font-medium select-none",
        "data-[disabled]:pointer-events-none data-[disabled]:cursor-not-allowed data-[disabled]:opacity-50",
        "data-[invalid]:text-destructive",
        props.class,
      )}
      {...rest}
    />
  )
}

export type SwitchErrorMessageProps<T extends ValidComponent = "div"> =
  ComponentProps<typeof SwitchPrimitive.ErrorMessage<T>>

export const SwitchErrorMessage = <T extends ValidComponent = "div">(
  props: SwitchErrorMessageProps<T>,
) => {
  const [, rest] = splitProps(props as SwitchErrorMessageProps, ["class"])

  return (
    <SwitchPrimitive.ErrorMessage
      data-slot="switch-error-message"
      class={cx("text-destructive text-sm", props.class)}
      {...rest}
    />
  )
}

export type SwitchDescriptionProps<T extends ValidComponent = "div"> =
  ComponentProps<typeof SwitchPrimitive.Description<T>>

export const SwitchDescription = <T extends ValidComponent = "div">(
  props: SwitchDescriptionProps<T>,
) => {
  const [, rest] = splitProps(props as SwitchDescriptionProps, ["class"])

  return (
    <SwitchPrimitive.Description
      data-slot="switch-description"
      class={cx("text-muted-foreground text-sm", props.class)}
      {...rest}
    />
  )
}
