// registry/react/ui/table.tsx
"use client"

import * as React from "react"

import { cn } from "@/lib/utils"

function Table({ className, ...props }: React.ComponentProps<"table">) {
  return (
    <div
      data-slot="table-container"
      className="relative w-full overflow-x-auto"
    >
      <table
        data-slot="table"
        className={cn("w-full caption-bottom text-sm", className)}
        {...props}
      />
    </div>
  )
}

function TableHeader({ className, ...props }: React.ComponentProps<"thead">) {
  return (
    <thead
      data-slot="table-header"
      className={cn("[&_tr]:border-b [&_tr]:border-border", className)}
      {...props}
    />
  )
}

function TableBody({ className, ...props }: React.ComponentProps<"tbody">) {
  return (
    <tbody
      data-slot="table-body"
      className={cn("[&_tr:last-child]:border-0", className)}
      {...props}
    />
  )
}

function TableFooter({ className, ...props }: React.ComponentProps<"tfoot">) {
  return (
    <tfoot
      data-slot="table-footer"
      className={cn(
        "border-t bg-transparent font-medium [&>tr]:last:border-b-0",
        className
      )}
      {...props}
    />
  )
}

function TableRow({ className, ...props }: React.ComponentProps<"tr">) {
  return (
    <tr
      data-slot="table-row"
      className={cn(
        "border-b border-border/80 transition-colors hover:bg-accent/50 has-aria-expanded:bg-accent/50 data-[state=selected]:bg-accent",
        className
      )}
      {...props}
    />
  )
}

function TableHead({ className, ...props }: React.ComponentProps<"th">) {
  return (
    <th
      data-slot="table-head"
      className={cn(
        "h-11 px-3 text-left align-middle text-xs font-semibold whitespace-nowrap text-foreground/80 [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
        className
      )}
      {...props}
    />
  )
}

function TableCell({ className, ...props }: React.ComponentProps<"td">) {
  return (
    <td
      data-slot="table-cell"
      className={cn(
        "p-3 align-middle whitespace-nowrap [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
        className
      )}
      {...props}
    />
  )
}

function TableCaption({
  className,
  ...props
}: React.ComponentProps<"caption">) {
  return (
    <caption
      data-slot="table-caption"
      className={cn("mt-4 text-sm text-muted-foreground", className)}
      {...props}
    />
  )
}

export {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
}

// registry/solid/ui/table.tsx
import type { ComponentProps } from "solid-js"
import { splitProps } from "solid-js"

import { cx } from "@/registry/solid/lib/cva"

export type TableProps = ComponentProps<"table">

export const Table = (props: TableProps) => {
  const [, rest] = splitProps(props, ["class"])

  return (
    <div data-slot="table-container" class="relative w-full overflow-x-auto">
      <table
        data-slot="table"
        class={cx("w-full caption-bottom text-sm", props.class)}
        {...rest}
      />
    </div>
  )
}

export type TableHeaderProps = ComponentProps<"thead">

export const TableHeader = (props: TableHeaderProps) => {
  const [, rest] = splitProps(props, ["class"])

  return (
    <thead
      data-slot="table-header"
      class={cx("[&_tr]:border-b [&_tr]:border-border", props.class)}
      {...rest}
    />
  )
}

export type TableBodyProps = ComponentProps<"tbody">

export const TableBody = (props: TableBodyProps) => {
  const [, rest] = splitProps(props, ["class"])

  return (
    <tbody
      data-slot="table-body"
      class={cx("[&_tr:last-child]:border-0", props.class)}
      {...rest}
    />
  )
}

export type TableFooterProps = ComponentProps<"tfoot">

export const TableFooter = (props: TableFooterProps) => {
  const [, rest] = splitProps(props, ["class"])

  return (
    <tfoot
      data-slot="table-footer"
      class={cx(
        "border-t bg-transparent font-medium [&>tr]:last:border-b-0",
        props.class,
      )}
      {...rest}
    />
  )
}

export type TableRowProps = ComponentProps<"tr">

export const TableRow = (props: TableRowProps) => {
  const [, rest] = splitProps(props, ["class"])

  return (
    <tr
      data-slot="table-row"
      class={cx(
        "border-b border-border/80 transition-colors hover:bg-accent/50 has-aria-expanded:bg-accent/50 data-[state=selected]:bg-accent",
        props.class,
      )}
      {...rest}
    />
  )
}

export type TableHeadProps = ComponentProps<"th">

export const TableHead = (props: TableHeadProps) => {
  const [, rest] = splitProps(props, ["class"])

  return (
    <th
      data-slot="table-head"
      class={cx(
        "h-11 px-3 text-left align-middle text-xs font-semibold whitespace-nowrap text-foreground/80 [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
        props.class,
      )}
      {...rest}
    />
  )
}

export type TableCellProps = ComponentProps<"td">

export const TableCell = (props: TableCellProps) => {
  const [, rest] = splitProps(props, ["class"])

  return (
    <td
      data-slot="table-cell"
      class={cx(
        "p-3 align-middle whitespace-nowrap [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
        props.class,
      )}
      {...rest}
    />
  )
}

export type TableCaptionProps = ComponentProps<"caption">

export const TableCaption = (props: TableCaptionProps) => {
  const [, rest] = splitProps(props, ["class"])

  return (
    <caption
      data-slot="table-caption"
      class={cx("text-muted-foreground mt-4 text-sm", props.class)}
      {...rest}
    />
  )
}
