// registry/react/ui/toggle-group.tsx
import * as React from "react"
import { Toggle as TogglePrimitive } from "@base-ui/react/toggle"
import { ToggleGroup as ToggleGroupPrimitive } from "@base-ui/react/toggle-group"
import { type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"
import { toggleVariants } from "@/registry/react/ui/toggle"

const ToggleGroupContext = React.createContext<
  VariantProps<typeof toggleVariants> & {
    spacing?: number
    orientation?: "horizontal" | "vertical"
  }
>({
  size: "default",
  variant: "default",
  spacing: 2,
  orientation: "horizontal",
})

function ToggleGroup({
  className,
  variant,
  size,
  spacing = 2,
  orientation = "horizontal",
  children,
  ...props
}: ToggleGroupPrimitive.Props &
  VariantProps<typeof toggleVariants> & {
    spacing?: number
    orientation?: "horizontal" | "vertical"
  }) {
  return (
    <ToggleGroupPrimitive
      data-slot="toggle-group"
      data-variant={variant}
      data-size={size}
      data-spacing={spacing}
      data-orientation={orientation}
      style={{ "--gap": spacing } as React.CSSProperties}
      className={cn(
        "group/toggle-group flex w-fit items-center gap-[--spacing(var(--gap))] rounded-full data-[spacing=0]:gap-0 data-[spacing=0]:border data-[spacing=0]:border-border data-[spacing=0]:bg-card data-[spacing=0]:p-0.5 data-vertical:flex-col data-vertical:items-stretch",
        className
      )}
      {...props}
    >
      <ToggleGroupContext.Provider
        value={{ variant, size, spacing, orientation }}
      >
        {children}
      </ToggleGroupContext.Provider>
    </ToggleGroupPrimitive>
  )
}

function ToggleGroupItem({
  className,
  children,
  variant = "default",
  size = "default",
  ...props
}: TogglePrimitive.Props & VariantProps<typeof toggleVariants>) {
  const context = React.useContext(ToggleGroupContext)

  return (
    <TogglePrimitive
      data-slot="toggle-group-item"
      data-variant={context.variant || variant}
      data-size={context.size || size}
      data-spacing={context.spacing}
      className={cn(
        "shrink-0 group-data-[spacing=0]/toggle-group:rounded-none group-data-[spacing=0]/toggle-group:px-2 focus:z-10 focus-visible:z-10 group-data-horizontal/toggle-group:data-[spacing=0]:first:rounded-l-full group-data-vertical/toggle-group:data-[spacing=0]:first:rounded-t-full group-data-horizontal/toggle-group:data-[spacing=0]:last:rounded-r-full group-data-vertical/toggle-group:data-[spacing=0]:last:rounded-b-full group-data-horizontal/toggle-group:data-[spacing=0]:data-[variant=outline]:border-l-0 group-data-vertical/toggle-group:data-[spacing=0]:data-[variant=outline]:border-t-0 group-data-horizontal/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-l group-data-vertical/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-t",
        toggleVariants({
          variant: context.variant || variant,
          size: context.size || size,
        }),
        className
      )}
      {...props}
    >
      {children}
    </TogglePrimitive>
  )
}

export { ToggleGroup, ToggleGroupItem }

// registry/solid/ui/toggle-group.tsx
import type { ComponentProps, ValidComponent } from "solid-js"
import { createContext, splitProps, useContext } from "solid-js"
import { ToggleGroup as ToggleGroupPrimitive } from "@kobalte/core/toggle-group"
import type { VariantProps } from "cva"

import { cx } from "@/registry/solid/lib/cva"

import { toggleButtonVariants } from "./toggle"

const ToggleGroupContext =
  createContext<
    VariantProps<typeof toggleButtonVariants> & {
      spacing?: number
      orientation?: "horizontal" | "vertical"
    }
  >()

export type ToggleGroupProps<T extends ValidComponent = "div"> = ComponentProps<
  typeof ToggleGroupPrimitive<T>
> &
  VariantProps<typeof toggleButtonVariants> & {
    spacing?: number
    orientation?: "horizontal" | "vertical"
  }

export const ToggleGroup = <T extends ValidComponent = "div">(
  props: ToggleGroupProps<T>,
) => {
  const [, rest] = splitProps(props as ToggleGroupProps, [
    "class",
    "variant",
    "size",
    "children",
    "spacing",
    "orientation",
  ])

  return (
    <ToggleGroupPrimitive
      data-slot="toggle-group"
      data-variant={props.variant}
      data-size={props.size}
      data-spacing={props.spacing ?? 2}
      data-orientation={props.orientation ?? "horizontal"}
      style={{ "--gap": `${props.spacing ?? 2}` }}
      class={cx(
        "group/toggle-group flex w-fit items-center gap-[--spacing(var(--gap))] rounded-full data-[spacing=0]:gap-0 data-[spacing=0]:border data-[spacing=0]:border-border data-[spacing=0]:bg-card data-[spacing=0]:p-0.5 data-[orientation=vertical]:flex-col data-[orientation=vertical]:items-stretch data-vertical:flex-col data-vertical:items-stretch",
        props.class,
      )}
      {...rest}
    >
      <ToggleGroupContext.Provider
        value={{
          get size() {
            return props.size
          },
          get variant() {
            return props.variant
          },
          get spacing() {
            return props.spacing ?? 2
          },
          get orientation() {
            return props.orientation ?? "horizontal"
          },
        }}
      >
        {props.children}
      </ToggleGroupContext.Provider>
    </ToggleGroupPrimitive>
  )
}

export type ToggleGroupItemProps<T extends ValidComponent = "button"> =
  ComponentProps<typeof ToggleGroupPrimitive.Item<T>> &
    VariantProps<typeof toggleButtonVariants>

export const ToggleGroupItem = <T extends ValidComponent = "button">(
  props: ToggleGroupItemProps<T>,
) => {
  const [, rest] = splitProps(props as ToggleGroupItemProps, [
    "class",
    "variant",
    "size",
  ])
  const context = useContext(ToggleGroupContext)

  return (
    <ToggleGroupPrimitive.Item
      data-slot="toggle-group-item"
      data-variant={context?.variant ?? props.variant}
      data-size={context?.size ?? props.size}
      data-spacing={context?.spacing}
      class={toggleButtonVariants({
        variant: context?.variant ?? props.variant,
        size: context?.size ?? props.size,
        class: [
          "shrink-0 group-data-[spacing=0]/toggle-group:rounded-none group-data-[spacing=0]/toggle-group:px-2 focus:z-10 focus-visible:z-10 group-data-[orientation=horizontal]/toggle-group:data-[spacing=0]:first:rounded-l-full group-data-[orientation=vertical]/toggle-group:data-[spacing=0]:first:rounded-t-full group-data-[orientation=horizontal]/toggle-group:data-[spacing=0]:last:rounded-r-full group-data-[orientation=vertical]/toggle-group:data-[spacing=0]:last:rounded-b-full group-data-[orientation=horizontal]/toggle-group:data-[spacing=0]:data-[variant=outline]:border-l-0 group-data-[orientation=vertical]/toggle-group:data-[spacing=0]:data-[variant=outline]:border-t-0 group-data-[orientation=horizontal]/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-l group-data-[orientation=vertical]/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-t group-data-horizontal/toggle-group:data-[spacing=0]:first:rounded-l-full group-data-vertical/toggle-group:data-[spacing=0]:first:rounded-t-full group-data-horizontal/toggle-group:data-[spacing=0]:last:rounded-r-full group-data-vertical/toggle-group:data-[spacing=0]:last:rounded-b-full",
          props.class,
        ],
      })}
      {...rest}
    />
  )
}
