// registry/solid/ui/carousel.tsx
import type {
  Accessor,
  ComponentProps,
  Setter,
  ValidComponent,
  VoidProps,
} from "solid-js"
import {
  createContext,
  createEffect,
  mergeProps,
  onCleanup,
  onMount,
  splitProps,
  useContext,
} from "solid-js"
import { createStore } from "solid-js/store"
import type { PolymorphicProps } from "@kobalte/core/polymorphic"
import type { CreateEmblaCarouselType } from "embla-carousel-solid"
import createEmblaCarousel from "embla-carousel-solid"

import { cx } from "@/registry/solid/lib/cva"

import type { ButtonProps } from "./button"
import { Button } from "./button"

type CarouselAPI = CreateEmblaCarouselType[1]
type CreateCarouselParameters = Parameters<typeof createEmblaCarousel>
type CarouselOptions = CreateCarouselParameters[0]
type CarouselPlugin = CreateCarouselParameters[1]

export interface CarouselOptionsProps {
  options?: CarouselOptions
  plugins?: CarouselPlugin
  orientation?: "horizontal" | "vertical"
  setAPI?: Setter<CarouselAPI>
}

export type CarouselProps = ComponentProps<"div"> & CarouselOptionsProps

type CarouselContextProps = {
  ref: ReturnType<typeof createEmblaCarousel>[0]
  api: ReturnType<typeof createEmblaCarousel>[1]
  scrollPrev: () => void
  scrollNext: () => void
  canScrollPrev: Accessor<boolean>
  canScrollNext: Accessor<boolean>
} & CarouselOptionsProps

const CarouselContext = createContext<CarouselContextProps | null>(null)

export const useCarousel = () => {
  const context = useContext(CarouselContext)

  if (!context) {
    throw new Error("useCarousel must be used within a <Carousel />")
  }

  return context
}

export const Carousel = (props: CarouselProps) => {
  const merge = mergeProps<CarouselProps[]>(
    {
      orientation: "horizontal",
    },
    props,
  )
  const [, rest] = splitProps(merge, [
    "orientation",
    "options",
    "setAPI",
    "plugins",
    "class",
    "children",
  ])

  const [ref, api] = createEmblaCarousel(
    () => ({
      ...merge.options?.(),
      axis: merge.orientation === "horizontal" ? "x" : "y",
    }),
    () => merge.plugins?.() ?? [],
  )

  const [store, setStore] = createStore({
    canScrollNext: false,
    canScrollPrev: false,
  })

  const onSelect = (api: CarouselAPI) => {
    if (!api()) return
    setStore({
      canScrollNext: api()!.canScrollNext(),
      canScrollPrev: api()!.canScrollPrev(),
    })
  }

  const scrollPrev = () => {
    api()?.scrollPrev()
  }

  const scrollNext = () => {
    api()?.scrollNext()
  }

  const handleKeyDown = (event: KeyboardEvent) => {
    if (event.key === "ArrowLeft") {
      event.preventDefault()
      scrollPrev()
    } else if (event.key === "ArrowRight") {
      event.preventDefault()
      scrollNext()
    }
  }

  onMount(() => {
    if (!api() || !merge.setAPI) return
    // @ts-expect-error - api should be defined
    merge.setAPI(api)
  })

  createEffect(() => {
    if (!api()) return
    onSelect(api)
    api()!.on("reInit", (api) => {
      onSelect(() => api)
    })
    api()!.on("select", (api) => {
      onSelect(() => api)
    })

    onCleanup(() => {
      api()!.off("select", (api) => {
        onSelect(() => api)
      })
    })
  })

  const value: CarouselContextProps = {
    ref,
    api,
    canScrollPrev: () => store.canScrollPrev,
    get options() {
      return merge.options
    },
    canScrollNext: () => store.canScrollNext,
    get orientation() {
      return (
        merge.orientation ??
        (merge.options?.().axis === "y" ? "vertical" : "horizontal")
      )
    },
    get plugins() {
      return merge.plugins
    },
    scrollNext,
    scrollPrev,
    get setAPI() {
      return merge.setAPI
    },
  }

  return (
    <CarouselContext.Provider value={value}>
      <div
        onKeyDown={handleKeyDown}
        class={cx("relative", merge.class)}
        role="region"
        aria-roledescription="carousel"
        data-slot="carousel"
        {...rest}
      >
        {merge.children}
      </div>
    </CarouselContext.Provider>
  )
}

export type CarouselContentProps = ComponentProps<"div">

export const CarouselContent = (props: CarouselContentProps) => {
  const { ref, orientation } = useCarousel()
  const [, rest] = splitProps(props, ["class"])

  return (
    <div ref={ref} class="overflow-hidden" data-slot="carousel-content">
      <div
        class={cx(
          "flex",
          orientation === "horizontal" ? "-ml-4" : "-mt-4 flex-col",
          props.class,
        )}
        {...rest}
      />
    </div>
  )
}

export type CarouselItemProps = ComponentProps<"div">

export const CarouselItem = (props: CarouselItemProps) => {
  const { orientation } = useCarousel()
  const [, rest] = splitProps(props, ["class"])

  return (
    <div
      role="group"
      aria-roledescription="slide"
      data-slot="carousel-item"
      class={cx(
        "min-w-0 shrink-0 grow-0 basis-full",
        orientation === "horizontal" ? "pl-4" : "pt-4",
        props.class,
      )}
      {...rest}
    />
  )
}

export type CarouselNextProps<T extends ValidComponent = "button"> = VoidProps<
  ButtonProps<T>
>

export const CarouselNext = <T extends ValidComponent = "button">(
  props: PolymorphicProps<T, CarouselNextProps<T>>,
) => {
  const { orientation, scrollNext, canScrollNext } = useCarousel()
  const merge = mergeProps<CarouselNextProps[]>(
    {
      variant: "outline",
      size: "icon",
    },
    props as CarouselNextProps,
  )
  const [, rest] = splitProps(merge, ["class", "variant", "size"])

  return (
    <Button
      data-slot="carousel-next"
      variant={merge.variant}
      size={merge.size}
      class={cx(
        "absolute size-8 rounded-full",
        orientation === "horizontal"
          ? "top-1/2 -right-12 -translate-y-1/2"
          : "-bottom-12 left-1/2 -translate-x-1/2 rotate-90",
        merge.class,
      )}
      disabled={!canScrollNext()}
      onClick={scrollNext}
      {...rest}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="size-4"
        viewBox="0 0 24 24"
      >
        <path
          fill="none"
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M5 12h14m-7-7l7 7l-7 7"
        />
      </svg>
    </Button>
  )
}

export type CarouselPreviousProps<T extends ValidComponent = "button"> =
  VoidProps<ButtonProps<T>>

export const CarouselPrevious = <T extends ValidComponent = "button">(
  props: PolymorphicProps<T, CarouselPreviousProps<T>>,
) => {
  const { orientation, scrollPrev, canScrollPrev } = useCarousel()
  const merge = mergeProps<CarouselPreviousProps[]>(
    {
      variant: "outline",
      size: "icon",
    },
    props as CarouselPreviousProps,
  )
  const [, rest] = splitProps(merge, ["class", "variant", "size"])

  return (
    <Button
      data-slot="carousel-previous"
      variant={merge.variant}
      size={merge.size}
      class={cx(
        "absolute size-8 rounded-full",
        orientation === "horizontal"
          ? "top-1/2 -left-12 -translate-y-1/2"
          : "-top-12 left-1/2 -translate-x-1/2 rotate-90",
        merge.class,
      )}
      disabled={!canScrollPrev()}
      onClick={scrollPrev}
      {...rest}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="size-4"
        viewBox="0 0 24 24"
      >
        <path
          fill="none"
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="m12 19l-7-7l7-7m7 7H5"
        />
      </svg>
    </Button>
  )
}

// registry/react/ui/carousel.tsx
"use client"

import * as React from "react"
import useEmblaCarousel, {
  type UseEmblaCarouselType,
} from "embla-carousel-react"
import { ArrowLeft, ArrowRight } from "lucide-react"

import { cn } from "@/lib/utils"
import { Button } from "@/registry/react/ui/button"

type CarouselApi = UseEmblaCarouselType[1]
type UseCarouselParameters = Parameters<typeof useEmblaCarousel>
type CarouselOptions = UseCarouselParameters[0]
type CarouselPlugin = UseCarouselParameters[1]

type CarouselProps = {
  opts?: CarouselOptions
  plugins?: CarouselPlugin
  orientation?: "horizontal" | "vertical"
  setApi?: (api: CarouselApi) => void
}

type CarouselContextProps = {
  carouselRef: ReturnType<typeof useEmblaCarousel>[0]
  api: ReturnType<typeof useEmblaCarousel>[1]
  scrollPrev: () => void
  scrollNext: () => void
  canScrollPrev: boolean
  canScrollNext: boolean
} & CarouselProps

const CarouselContext = React.createContext<CarouselContextProps | null>(null)

function useCarousel() {
  const context = React.useContext(CarouselContext)

  if (!context) {
    throw new Error("useCarousel must be used within a <Carousel />")
  }

  return context
}

function Carousel({
  orientation = "horizontal",
  opts,
  setApi,
  plugins,
  className,
  children,
  ...props
}: React.ComponentProps<"div"> & CarouselProps) {
  const [carouselRef, api] = useEmblaCarousel(
    {
      ...opts,
      axis: orientation === "horizontal" ? "x" : "y",
    },
    plugins
  )
  const [canScrollPrev, setCanScrollPrev] = React.useState(false)
  const [canScrollNext, setCanScrollNext] = React.useState(false)

  const onSelect = React.useCallback((api: CarouselApi) => {
    if (!api) return
    setCanScrollPrev(api.canScrollPrev())
    setCanScrollNext(api.canScrollNext())
  }, [])

  const scrollPrev = React.useCallback(() => {
    api?.scrollPrev()
  }, [api])

  const scrollNext = React.useCallback(() => {
    api?.scrollNext()
  }, [api])

  const handleKeyDown = React.useCallback(
    (event: React.KeyboardEvent<HTMLDivElement>) => {
      if (event.key === "ArrowLeft") {
        event.preventDefault()
        scrollPrev()
      } else if (event.key === "ArrowRight") {
        event.preventDefault()
        scrollNext()
      }
    },
    [scrollPrev, scrollNext]
  )

  React.useEffect(() => {
    if (!api || !setApi) return
    setApi(api)
  }, [api, setApi])

  React.useEffect(() => {
    if (!api) return
    onSelect(api)
    api.on("reInit", onSelect)
    api.on("select", onSelect)

    return () => {
      api?.off("select", onSelect)
    }
  }, [api, onSelect])

  return (
    <CarouselContext.Provider
      value={{
        carouselRef,
        api: api,
        opts,
        orientation:
          orientation || (opts?.axis === "y" ? "vertical" : "horizontal"),
        scrollPrev,
        scrollNext,
        canScrollPrev,
        canScrollNext,
      }}
    >
      <div
        onKeyDownCapture={handleKeyDown}
        className={cn("relative", className)}
        role="region"
        aria-roledescription="carousel"
        data-slot="carousel"
        {...props}
      >
        {children}
      </div>
    </CarouselContext.Provider>
  )
}

function CarouselContent({ className, ...props }: React.ComponentProps<"div">) {
  const { carouselRef, orientation } = useCarousel()

  return (
    <div
      ref={carouselRef}
      className="overflow-hidden"
      data-slot="carousel-content"
    >
      <div
        className={cn(
          "flex",
          orientation === "horizontal" ? "-ml-4" : "-mt-4 flex-col",
          className
        )}
        {...props}
      />
    </div>
  )
}

function CarouselItem({ className, ...props }: React.ComponentProps<"div">) {
  const { orientation } = useCarousel()

  return (
    <div
      role="group"
      aria-roledescription="slide"
      data-slot="carousel-item"
      className={cn(
        "min-w-0 shrink-0 grow-0 basis-full",
        orientation === "horizontal" ? "pl-4" : "pt-4",
        className
      )}
      {...props}
    />
  )
}

function CarouselPrevious({
  className,
  variant = "outline",
  size = "icon",
  ...props
}: React.ComponentProps<typeof Button>) {
  const { orientation, scrollPrev, canScrollPrev } = useCarousel()

  return (
    <Button
      data-slot="carousel-previous"
      variant={variant}
      size={size}
      className={cn(
        "absolute size-8 rounded-full",
        orientation === "horizontal"
          ? "top-1/2 -left-12 -translate-y-1/2"
          : "-top-12 left-1/2 -translate-x-1/2 rotate-90",
        className
      )}
      disabled={!canScrollPrev}
      onClick={scrollPrev}
      {...props}
    >
      <ArrowLeft />
      <span className="sr-only">Previous slide</span>
    </Button>
  )
}

function CarouselNext({
  className,
  variant = "outline",
  size = "icon",
  ...props
}: React.ComponentProps<typeof Button>) {
  const { orientation, scrollNext, canScrollNext } = useCarousel()

  return (
    <Button
      data-slot="carousel-next"
      variant={variant}
      size={size}
      className={cn(
        "absolute size-8 rounded-full",
        orientation === "horizontal"
          ? "top-1/2 -right-12 -translate-y-1/2"
          : "-bottom-12 left-1/2 -translate-x-1/2 rotate-90",
        className
      )}
      disabled={!canScrollNext}
      onClick={scrollNext}
      {...props}
    >
      <ArrowRight />
      <span className="sr-only">Next slide</span>
    </Button>
  )
}

export {
  type CarouselApi,
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselPrevious,
  CarouselNext,
}
