// registry/solid/ui/menubar.tsx
import {
  mergeProps,
  splitProps,
  type ComponentProps,
  type ValidComponent,
} from "solid-js"
import { Menubar as MenubarPrimitive } from "@kobalte/core/menubar"

import { cx } from "@/registry/solid/lib/cva"

export const MenubarPortal = MenubarPrimitive.Portal

export type MenubarProps<T extends ValidComponent = "div"> = ComponentProps<
  typeof MenubarPrimitive<T>
>

export const Menubar = <T extends ValidComponent = "div">(
  props: MenubarProps<T>,
) => {
  const [, rest] = splitProps(props as MenubarProps, ["class"])

  return (
    <MenubarPrimitive
      data-slot="menubar"
      class={cx(
        "flex h-9 items-center gap-1 rounded-md border border-border bg-card p-1",
        props.class,
      )}
      {...rest}
    />
  )
}

export type MenubarMenuProps = ComponentProps<typeof MenubarPrimitive.Menu>

export const MenubarMenu = (props: MenubarMenuProps) => {
  const merge = mergeProps<MenubarMenuProps[]>(
    {
      gutter: 8,
    },
    props,
  )

  return <MenubarPrimitive.Menu data-slot="menubar-menu" {...merge} />
}

export type MenubarGroupProps = ComponentProps<typeof MenubarPrimitive.Group>

export const MenubarGroup = (props: MenubarGroupProps) => {
  return <MenubarPrimitive.Group data-slot="menubar-group" {...props} />
}

export type MenubarRadioGroupProps = ComponentProps<
  typeof MenubarPrimitive.RadioGroup
>

export const MenubarRadioGroup = (props: MenubarRadioGroupProps) => {
  return (
    <MenubarPrimitive.RadioGroup data-slot="menubar-radio-group" {...props} />
  )
}

export type MenubarTriggerProps<T extends ValidComponent = "button"> =
  ComponentProps<typeof MenubarPrimitive.Trigger<T>>

export const MenubarTrigger = <T extends ValidComponent = "button">(
  props: MenubarTriggerProps<T>,
) => {
  const [, rest] = splitProps(props as MenubarTriggerProps, ["class"])

  return (
    <MenubarPrimitive.Trigger
      data-slot="menubar-trigger"
      class={cx(
        "flex h-7 items-center rounded-md px-2.5 text-sm font-medium outline-hidden select-none focus:bg-primary/10 focus:text-foreground data-[expanded]:bg-primary/10 data-[expanded]:text-foreground",
        props.class,
      )}
      {...rest}
    />
  )
}

export type MenubarContentProps<T extends ValidComponent = "div"> =
  ComponentProps<typeof MenubarPrimitive.Content<T>>

export const MenubarContent = <T extends ValidComponent = "div">(
  props: MenubarContentProps<T>,
) => {
  const [, rest] = splitProps(props as MenubarContentProps, ["class"])

  return (
    <MenubarPrimitive.Content
      data-slot="menubar-content"
      class={cx(
        "z-50 min-w-[12rem] origin-(--kb-menu-content-transform-origin) overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md focus-visible:outline-none data-[expanded]:animate-in data-[expanded]:fade-in-0 data-[expanded]:zoom-in-95 data-[closed]:animate-out data-[closed]:fade-out-0 data-[closed]:zoom-out-95",
        "[[data-popper-positioner][style*='--kb-popper-content-transform-origin:_top']>[data-slot=menubar-content]]:slide-in-from-top-2 [[data-popper-positioner][style*='--kb-popper-content-transform-origin:_bottom']>[data-slot=menubar-content]]:slide-in-from-bottom-2 [[data-popper-positioner][style*='--kb-popper-content-transform-origin:_left']>[data-slot=menubar-content]]:slide-in-from-left-2 [[data-popper-positioner][style*='--kb-popper-content-transform-origin:_right']>[data-slot=menubar-content]]:slide-in-from-right-2",
        props.class,
      )}
      {...rest}
    />
  )
}

export type MenubarItemProps<T extends ValidComponent = "div"> = ComponentProps<
  typeof MenubarPrimitive.Item<T>
> & {
  inset?: boolean
  variant?: "default" | "destructive"
}

export const MenubarItem = <T extends ValidComponent = "div">(
  props: MenubarItemProps<T>,
) => {
  const merge = mergeProps(
    {
      variant: "default",
    } as MenubarItemProps,
    props,
  )
  const [, rest] = splitProps(merge, ["class", "inset", "variant"])

  return (
    <MenubarPrimitive.Item
      data-slot="menubar-item"
      data-inset={props.inset}
      data-variant={props.variant}
      class={cx(
        "relative flex h-8 cursor-default items-center gap-2 rounded-md px-2.5 text-sm outline-hidden select-none focus:bg-primary/10 focus:text-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50 data-[inset]:pl-8 data-[variant=destructive]:text-destructive data-[variant=destructive]:focus:bg-destructive/10 data-[variant=destructive]:focus:text-destructive dark:data-[variant=destructive]:focus:bg-destructive/20 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground data-[variant=destructive]:*:[svg]:text-destructive!",
        props.class,
      )}
      {...rest}
    />
  )
}

export type MenubarCheckboxItemProps<T extends ValidComponent = "div"> =
  ComponentProps<typeof MenubarPrimitive.CheckboxItem<T>>

export const MenubarCheckboxItem = <T extends ValidComponent = "div">(
  props: MenubarCheckboxItemProps<T>,
) => {
  const [, rest] = splitProps(props as MenubarCheckboxItemProps, [
    "class",
    "children",
  ])

  return (
    <MenubarPrimitive.CheckboxItem
      data-slot="menubar-checkbox-item"
      class={cx(
        "relative flex h-8 cursor-default items-center gap-2 rounded-md pr-2.5 pl-8 text-sm outline-hidden select-none focus:bg-primary/10 focus:text-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
        props.class,
      )}
      {...rest}
    >
      <span class="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center">
        <MenubarPrimitive.ItemIndicator>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="size-4"
            viewBox="0 0 24 24"
          >
            <path
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M20 6L9 17l-5-5"
            />
          </svg>
        </MenubarPrimitive.ItemIndicator>
      </span>
      {props.children}
    </MenubarPrimitive.CheckboxItem>
  )
}

export type MenubarRadioItemProps<T extends ValidComponent = "div"> =
  ComponentProps<typeof MenubarPrimitive.RadioItem<T>>

export const MenubarRadioItem = <T extends ValidComponent = "div">(
  props: MenubarRadioItemProps<T>,
) => {
  const [, rest] = splitProps(props as MenubarRadioItemProps, [
    "class",
    "children",
  ])

  return (
    <MenubarPrimitive.RadioItem
      data-slot="menubar-radio-item"
      class={cx(
        "relative flex h-8 cursor-default items-center gap-2 rounded-md py-1.5 pr-2.5 pl-8 text-sm outline-hidden select-none focus:bg-primary/10 focus:text-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
        props.class,
      )}
      {...rest}
    >
      <span class="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center">
        <MenubarPrimitive.ItemIndicator>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            class="size-2"
          >
            <g
              fill="none"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
            >
              <path d="M0 0h24v24H0z" />
              <path
                fill="currentColor"
                d="M7 3.34a10 10 0 1 1-4.995 8.984L2 12l.005-.324A10 10 0 0 1 7 3.34"
              />
            </g>
          </svg>
        </MenubarPrimitive.ItemIndicator>
      </span>
      {props.children}
    </MenubarPrimitive.RadioItem>
  )
}

export type MenubarGroupLabelProps<T extends ValidComponent = "span"> =
  ComponentProps<typeof MenubarPrimitive.GroupLabel<T>> & {
    inset?: boolean
  }

export const MenubarGroupLabel = <T extends ValidComponent = "span">(
  props: MenubarGroupLabelProps<T>,
) => {
  const [, rest] = splitProps(props as MenubarGroupLabelProps, [
    "class",
    "inset",
  ])

  return (
    <MenubarPrimitive.GroupLabel
      data-slot="menubar-label"
      data-inset={props.inset}
      class={cx(
        "px-2.5 py-1.5 text-xs font-semibold text-muted-foreground data-[inset]:pl-8",
        props.class,
      )}
      {...rest}
    />
  )
}

export type MenubarItemLabelProps<T extends ValidComponent = "div"> =
  ComponentProps<typeof MenubarPrimitive.ItemLabel<T>> & {
    inset?: boolean
  }

export const MenubarItemLabel = <T extends ValidComponent = "div">(
  props: MenubarItemLabelProps<T>,
) => {
  const [, rest] = splitProps(props as MenubarItemLabelProps, [
    "class",
    "inset",
  ])

  return (
    <MenubarPrimitive.ItemLabel
      data-slot="menubar-item-label"
      data-inset={props.inset}
      class={cx(
        "px-2 py-1.5 text-sm font-medium data-[inset]:pl-8",
        props.class,
      )}
      {...rest}
    />
  )
}

export type MenubarSeparatorProps<T extends ValidComponent = "hr"> =
  ComponentProps<typeof MenubarPrimitive.Separator<T>>

export const MenubarSeparator = <T extends ValidComponent = "hr">(
  props: MenubarSeparatorProps<T>,
) => {
  const [, rest] = splitProps(props as MenubarSeparatorProps, ["class"])

  return (
    <MenubarPrimitive.Separator
      data-slot="menubar-separator"
      class={cx("bg-border -mx-1 my-1 h-px", props.class)}
      {...rest}
    />
  )
}

export type MenubarShortcut = ComponentProps<"span">

export const MenubarShortcut = (props: MenubarShortcut) => {
  const [, rest] = splitProps(props, ["class"])

  return (
    <span
      data-slot="menubar-shortcut"
      class={cx(
        "text-muted-foreground ml-auto text-xs tracking-widest",
        props.class,
      )}
      {...rest}
    />
  )
}

export type MenubarSubProps = ComponentProps<typeof MenubarPrimitive.Sub>

export const MenubarSub = (props: MenubarSubProps) => {
  return <MenubarPrimitive.Sub data-slot="menubar-sub" {...props} />
}

export type MenubarSubTriggerProps<T extends ValidComponent = "div"> =
  ComponentProps<typeof MenubarPrimitive.SubTrigger<T>> & {
    inset?: boolean
  }

export const MenubarSubTrigger = <T extends ValidComponent = "div">(
  props: MenubarSubTriggerProps<T>,
) => {
  const [, rest] = splitProps(props as MenubarSubTriggerProps, [
    "class",
    "inset",
    "children",
  ])

  return (
    <MenubarPrimitive.SubTrigger
      data-slot="menubar-sub-trigger"
      data-inset={props.inset}
      class={cx(
        "flex h-8 cursor-default items-center rounded-md px-2.5 text-sm outline-none select-none focus:bg-primary/10 focus:text-foreground data-[expanded]:bg-primary/10 data-[expanded]:text-foreground data-[inset]:pl-8 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground",
        props.class,
      )}
      {...rest}
    >
      {props.children}
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="ml-auto size-4"
        viewBox="0 0 24 24"
      >
        <path
          fill="none"
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="m9 18l6-6l-6-6"
        />
      </svg>
    </MenubarPrimitive.SubTrigger>
  )
}

export type MenubarSubContentProps<T extends ValidComponent = "div"> =
  ComponentProps<typeof MenubarPrimitive.SubContent<T>>

export const MenubarSubContent = <T extends ValidComponent = "div">(
  props: MenubarSubContentProps<T>,
) => {
  const [, rest] = splitProps(props as MenubarSubContentProps, ["class"])

  return (
    <MenubarPrimitive.SubContent
      data-slot="menubar-sub-content"
      class={cx(
        "z-50 min-w-[8rem] origin-(--kb-menu-content-transform-origin) overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-lg focus-visible:outline-none data-[expanded]:animate-in data-[expanded]:fade-in-0 data-[expanded]:zoom-in-95 data-[closed]:animate-out data-[closed]:fade-out-0 data-[closed]:zoom-out-95",
        "[[data-popper-positioner][style*='--kb-popper-content-transform-origin:_top']>[data-slot=menubar-sub-content]]:slide-in-from-top-2 [[data-popper-positioner][style*='--kb-popper-content-transform-origin:_bottom']>[data-slot=menubar-sub-content]]:slide-in-from-bottom-2 [[data-popper-positioner][style*='--kb-popper-content-transform-origin:_left']>[data-slot=menubar-sub-content]]:slide-in-from-left-2 [[data-popper-positioner][style*='--kb-popper-content-transform-origin:_right']>[data-slot=menubar-sub-content]]:slide-in-from-right-2",
        props.class,
      )}
      {...rest}
    />
  )
}


export const MenubarLabel = MenubarGroupLabel

// registry/react/ui/menubar.tsx
"use client"

import * as React from "react"
import { CheckIcon, ChevronRightIcon, CircleIcon } from "lucide-react"
import { Menubar as MenubarPrimitive } from "radix-ui"

import { cn } from "@/lib/utils"

function Menubar({
  className,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Root>) {
  return (
    <MenubarPrimitive.Root
      data-slot="menubar"
      className={cn(
        "flex h-9 items-center gap-1 rounded-md border border-border bg-card p-1",
        className
      )}
      {...props}
    />
  )
}

function MenubarMenu({
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Menu>) {
  return <MenubarPrimitive.Menu data-slot="menubar-menu" {...props} />
}

function MenubarGroup({
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Group>) {
  return <MenubarPrimitive.Group data-slot="menubar-group" {...props} />
}

function MenubarPortal({
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Portal>) {
  return <MenubarPrimitive.Portal data-slot="menubar-portal" {...props} />
}

function MenubarRadioGroup({
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.RadioGroup>) {
  return (
    <MenubarPrimitive.RadioGroup data-slot="menubar-radio-group" {...props} />
  )
}

function MenubarTrigger({
  className,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Trigger>) {
  return (
    <MenubarPrimitive.Trigger
      data-slot="menubar-trigger"
      className={cn(
        "flex h-7 items-center rounded-md px-2.5 text-sm font-medium outline-hidden select-none focus:bg-primary/10 focus:text-foreground data-[state=open]:bg-primary/10 data-[state=open]:text-foreground",
        className
      )}
      {...props}
    />
  )
}

function MenubarContent({
  className,
  align = "start",
  alignOffset = -4,
  sideOffset = 8,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Content>) {
  return (
    <MenubarPortal>
      <MenubarPrimitive.Content
        data-slot="menubar-content"
        align={align}
        alignOffset={alignOffset}
        sideOffset={sideOffset}
        className={cn(
          "z-50 min-w-[12rem] origin-(--radix-menubar-content-transform-origin) overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95",
          className
        )}
        {...props}
      />
    </MenubarPortal>
  )
}

function MenubarItem({
  className,
  inset,
  variant = "default",
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Item> & {
  inset?: boolean
  variant?: "default" | "destructive"
}) {
  return (
    <MenubarPrimitive.Item
      data-slot="menubar-item"
        data-inset={inset}
        data-variant={variant}
        className={cn(
        "relative flex h-8 cursor-default items-center gap-2 rounded-md px-2.5 text-sm outline-hidden select-none focus:bg-primary/10 focus:text-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50 data-[inset]:pl-8 data-[variant=destructive]:text-destructive data-[variant=destructive]:focus:bg-destructive/10 data-[variant=destructive]:focus:text-destructive dark:data-[variant=destructive]:focus:bg-destructive/20 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground data-[variant=destructive]:*:[svg]:text-destructive!",
        className
      )}
      {...props}
    />
  )
}

function MenubarCheckboxItem({
  className,
  children,
  checked,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.CheckboxItem>) {
  return (
    <MenubarPrimitive.CheckboxItem
      data-slot="menubar-checkbox-item"
      className={cn(
        "relative flex h-8 cursor-default items-center gap-2 rounded-md pr-2.5 pl-8 text-sm outline-hidden select-none focus:bg-primary/10 focus:text-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
        className
      )}
      checked={checked}
      {...props}
    >
      <span className="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center">
        <MenubarPrimitive.ItemIndicator>
          <CheckIcon className="size-4" />
        </MenubarPrimitive.ItemIndicator>
      </span>
      {children}
    </MenubarPrimitive.CheckboxItem>
  )
}

function MenubarRadioItem({
  className,
  children,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.RadioItem>) {
  return (
    <MenubarPrimitive.RadioItem
      data-slot="menubar-radio-item"
      className={cn(
        "relative flex h-8 cursor-default items-center gap-2 rounded-md pr-2.5 pl-8 text-sm outline-hidden select-none focus:bg-primary/10 focus:text-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
        className
      )}
      {...props}
    >
      <span className="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center">
        <MenubarPrimitive.ItemIndicator>
          <CircleIcon className="size-2 fill-current" />
        </MenubarPrimitive.ItemIndicator>
      </span>
      {children}
    </MenubarPrimitive.RadioItem>
  )
}

function MenubarLabel({
  className,
  inset,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Label> & {
  inset?: boolean
}) {
  return (
    <MenubarPrimitive.Label
      data-slot="menubar-label"
      data-inset={inset}
      className={cn(
        "px-2.5 py-1.5 text-xs font-semibold text-muted-foreground data-[inset]:pl-8",
        className
      )}
      {...props}
    />
  )
}

function MenubarSeparator({
  className,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Separator>) {
  return (
    <MenubarPrimitive.Separator
      data-slot="menubar-separator"
      className={cn("-mx-1 my-1 h-px bg-border", className)}
      {...props}
    />
  )
}

function MenubarShortcut({
  className,
  ...props
}: React.ComponentProps<"span">) {
  return (
    <span
      data-slot="menubar-shortcut"
      className={cn(
        "ml-auto text-xs tracking-widest text-muted-foreground",
        className
      )}
      {...props}
    />
  )
}

function MenubarSub({
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Sub>) {
  return <MenubarPrimitive.Sub data-slot="menubar-sub" {...props} />
}

function MenubarSubTrigger({
  className,
  inset,
  children,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.SubTrigger> & {
  inset?: boolean
}) {
  return (
    <MenubarPrimitive.SubTrigger
      data-slot="menubar-sub-trigger"
      data-inset={inset}
      className={cn(
        "flex h-8 cursor-default items-center rounded-md px-2.5 text-sm outline-none select-none focus:bg-primary/10 focus:text-foreground data-[inset]:pl-8 data-[state=open]:bg-primary/10 data-[state=open]:text-foreground",
        className
      )}
      {...props}
    >
      {children}
      <ChevronRightIcon className="ml-auto h-4 w-4" />
    </MenubarPrimitive.SubTrigger>
  )
}

function MenubarSubContent({
  className,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.SubContent>) {
  return (
    <MenubarPrimitive.SubContent
      data-slot="menubar-sub-content"
      className={cn(
        "z-50 min-w-[8rem] origin-(--radix-menubar-content-transform-origin) overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95",
        className
      )}
      {...props}
    />
  )
}

export {
  Menubar,
  MenubarPortal,
  MenubarMenu,
  MenubarTrigger,
  MenubarContent,
  MenubarGroup,
  MenubarSeparator,
  MenubarLabel,
  MenubarItem,
  MenubarShortcut,
  MenubarCheckboxItem,
  MenubarRadioGroup,
  MenubarRadioItem,
  MenubarSub,
  MenubarSubTrigger,
  MenubarSubContent,
}
