// registry/solid/ui/progress.tsx
import { splitProps, type JSX } from "solid-js"
import { cn } from "@/registry/solid/lib/utils"
function Progress(props: JSX.HTMLAttributes<HTMLDivElement> & { value?: number }) { const [l,r]=splitProps(props,["class","value","children"]); const value=l.value ?? 0; return <div data-slot="progress" role="progressbar" aria-valuenow={value} class={cn("relative h-2 w-full overflow-hidden rounded-full bg-border/70",l.class)} {...r}>{l.children}<ProgressTrack><ProgressIndicator style={{ width: value + "%" }} /></ProgressTrack></div> }
function ProgressTrack(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="progress-track" class={cn("relative flex h-full w-full items-center overflow-x-hidden rounded-full bg-border/70",l.class)} {...r}/> }
function ProgressIndicator(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="progress-indicator" class={cn("h-full bg-primary transition-all",l.class)} {...r}/> }
function ProgressLabel(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="progress-label" class={cn("text-sm font-medium",l.class)} {...r}/> }
function ProgressValue(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="progress-value" class={cn("ml-auto text-sm text-muted-foreground tabular-nums",l.class)} {...r}/> }
export { Progress, ProgressTrack, ProgressIndicator, ProgressLabel, ProgressValue }

// registry/react/ui/progress.tsx
"use client"

import { Progress as ProgressPrimitive } from "@base-ui/react/progress"

import { cn } from "@/lib/utils"

function Progress({
  className,
  children,
  value,
  ...props
}: ProgressPrimitive.Root.Props) {
  return (
    <ProgressPrimitive.Root
      value={value}
      data-slot="progress"
      className={cn("relative h-2 w-full overflow-hidden rounded-full bg-border/70", className)}
      {...props}
    >
      {children}
      <ProgressTrack>
        <ProgressIndicator />
      </ProgressTrack>
    </ProgressPrimitive.Root>
  )
}

function ProgressTrack({ className, ...props }: ProgressPrimitive.Track.Props) {
  return (
    <ProgressPrimitive.Track
      className={cn(
        "relative flex h-full w-full items-center overflow-x-hidden rounded-full bg-border/70",
        className
      )}
      data-slot="progress-track"
      {...props}
    />
  )
}

function ProgressIndicator({
  className,
  ...props
}: ProgressPrimitive.Indicator.Props) {
  return (
    <ProgressPrimitive.Indicator
      data-slot="progress-indicator"
      className={cn("h-full bg-primary transition-all", className)}
      {...props}
    />
  )
}

function ProgressLabel({ className, ...props }: ProgressPrimitive.Label.Props) {
  return (
    <ProgressPrimitive.Label
      className={cn("text-sm font-medium", className)}
      data-slot="progress-label"
      {...props}
    />
  )
}

function ProgressValue({ className, ...props }: ProgressPrimitive.Value.Props) {
  return (
    <ProgressPrimitive.Value
      className={cn(
        "ml-auto text-sm text-muted-foreground tabular-nums",
        className
      )}
      data-slot="progress-value"
      {...props}
    />
  )
}

export {
  Progress,
  ProgressTrack,
  ProgressIndicator,
  ProgressLabel,
  ProgressValue,
}
