// apps/demo/src/components/component-preview-react.tsx
import * as React from "react"
import { createRoot, type Root } from "react-dom/client"

const roots = new WeakMap<Element, Root>()
const reactDemo = import("./react-demo")

;(globalThis as typeof globalThis & { React: typeof React }).React = React

async function mountReactPreview(element: Element, name: string) {
  let root = roots.get(element)
  if (!root) {
    root = createRoot(element)
    roots.set(element, root)
  }

  const { default: ReactDemo } = await reactDemo
  root.render(React.createElement(ReactDemo, { name }))
}

function mountReactPreviews() {
  document
    .querySelectorAll('[data-component-preview="react"]')
    .forEach((element) => {
      const name = element.getAttribute("data-component-name")

      if (name) mountReactPreview(element, name)
    })
}

mountReactPreviews()

document.addEventListener("astro:after-swap", mountReactPreviews)

// apps/demo/src/components/component-preview-solid.tsx
import h from "solid-js/h"
import { render } from "solid-js/web"

const roots = new WeakMap<Element, () => void>()
const solidDemo = import("./solid-demo")

const solidRuntime = { createElement: h, Fragment: h.Fragment }

async function mountSolidPreview(element: Element, name: string) {
  if (roots.has(element)) return

  const previousRuntime = (globalThis as typeof globalThis & { React?: unknown }).React
  ;(globalThis as typeof globalThis & { React: typeof solidRuntime }).React =
    solidRuntime

  const { default: SolidDemo } = await solidDemo
  const dispose = render(() => solidRuntime.createElement(SolidDemo, { name }), element)
  roots.set(element, dispose)

  ;(globalThis as typeof globalThis & { React?: unknown }).React = previousRuntime
}

function mountSolidPreviews() {
  document
    .querySelectorAll('[data-component-preview="solid"]')
    .forEach((element) => {
      const name = element.getAttribute("data-component-name")

      if (name) mountSolidPreview(element, name)
    })
}

mountSolidPreviews()

document.addEventListener("astro:after-swap", mountSolidPreviews)
